# Optional total fuzzing time-out in seconds.
timeout: 60

# If present, ask the coverage monitor to generate a report after the time-out passes.
report: true

# Must be one of {'json', 'human-readable'}
output_format: human-readable

# The path to the open api specification of the target.
openapi_spec: openapi.json

## Must be one of {'off', 'error', 'warn', 'info', 'debug', 'trace'}
log_level: info

## The path to an initial corpus given in yaml.
initial_corpus: corpus_directory

## Per-request time-out in milliseconds. Defaults to 30 seconds.
# request_timeout: 30000

## If present, reproduces the crash given an input file, then quits.
# reproduce: test_request.yaml

## How to log in to the API server, if applicable. See login.md.
authentication: login.yaml
