version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "all"  # includes indirect dependencies
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "ThomasTNO"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "actions"