[alias]
dev-build = "build --no-default-features --features sequence-diagnostics"
dev-run = "run --no-default-features --features sequence-diagnostics"
dev-test = "test --no-default-features --features sequence-diagnostics"
