//! Loads an OpenAPI specification from a file, and converts it to the format we use.

use std::path::Path;

use anyhow::{Context, Result};
use openapiv3::VersionedOpenAPI;

use super::Spec;

/// AttemptsFailed records a parallel set of errors, that result from multiple
/// strategies failing. When Displayed, it prints all error chains that resulted
/// from the different attempts, so the user can find the strategy they wanted
/// to use and fix the errors that resulted in that attempt.
#[derive(Debug)]
struct AttemptsFailed {
    errors: Vec<anyhow::Error>,
}

impl std::fmt::Display for AttemptsFailed {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (i, err) in self.errors.iter().enumerate() {
            writeln!(f, "{i}. {err}")?;
            for cause in err.chain().skip(1) {
                writeln!(f, "     because: {cause}")?;
            }
        }
        Ok(())
    }
}

impl std::error::Error for AttemptsFailed {}

/// Placeholder used when a spec's `info.title` is missing, null, or empty.
/// Used only to make the spec parseable; not used for fuzzing.
const DEFAULT_INFO_TITLE: &str = "Untitled API";

/// Placeholder used when a spec's `info.version` is missing, null, or empty.
/// Used only to make the spec parseable; not used for fuzzing.
const DEFAULT_INFO_VERSION: &str = "0.0.0";

/// Some real-world OpenAPI specs (e.g. generated by springdoc-openapi) omit
/// `info.title`/`info.version`, or leave them blank, even though both are
/// required fields in the OpenAPI specification. All of our parsing
/// strategies therefore reject them outright with an unhelpful "missing field
/// `title`" error, even though these fields are irrelevant to fuzzing.
///
/// This patches the raw file contents (parsed generically, so it works for
/// both JSON and YAML input) by inserting placeholder values for any missing,
/// null, or empty `info.title`/`info.version` fields, logging a warning for
/// each one patched. If both fields are already present and non-empty, the
/// original `contents` is returned completely unchanged.
fn fill_in_missing_info_fields(contents: &str, filename: &Path) -> String {
    let Ok(mut doc) = serde_yaml::from_str::<serde_yaml::Value>(contents) else {
        // Not parseable even generically; let the real parsing attempts
        // further down produce the actual error message.
        return contents.to_string();
    };

    let is_blank = |value: Option<&serde_yaml::Value>| match value {
        None | Some(serde_yaml::Value::Null) => true,
        Some(serde_yaml::Value::String(s)) => s.is_empty(),
        _ => false,
    };

    let Some(mapping) = doc.as_mapping_mut() else {
        return contents.to_string();
    };

    let info = mapping
        .entry(serde_yaml::Value::String("info".to_string()))
        .or_insert_with(|| serde_yaml::Value::Mapping(Default::default()));
    let Some(info) = info.as_mapping_mut() else {
        return contents.to_string();
    };

    let mut patched = false;
    for (field, default) in [
        ("title", DEFAULT_INFO_TITLE),
        ("version", DEFAULT_INFO_VERSION),
    ] {
        let key = serde_yaml::Value::String(field.to_string());
        if is_blank(info.get(&key)) {
            log::warn!(
                "OpenAPI spec at {} is missing info.{field}; using placeholder value {default:?}",
                filename.to_string_lossy()
            );
            info.insert(key, serde_yaml::Value::String(default.to_string()));
            patched = true;
        }
    }

    if !patched {
        return contents.to_string();
    }
    serde_yaml::to_string(&doc).unwrap_or_else(|_| contents.to_string())
}

pub fn openapi_from_file(filename: &Path) -> Result<Spec> {
    let file_contents = std::fs::read_to_string(filename)?;
    let file_contents = fill_in_missing_info_fields(&file_contents, filename);
    let mut errors = Vec::new();

    match oas3::from_yaml(&file_contents).context("Failed to parse as YAML OpenAPI v3.1") {
        Ok(spec) => {
            return Ok(spec.into());
        }
        Err(err) => errors.push(err),
    };
    match oas3::from_json(&file_contents).context("Failed to parse as JSON OpenAPI v3.1") {
        Ok(spec) => return Ok(spec.into()),
        Err(err) => errors.push(err),
    };

    match serde_yaml::from_str::<VersionedOpenAPI>(&file_contents)
        .context("Failed to parse as YAML OpenAPI v2/v3.0")
    {
        Ok(spec) => match upgrade_versioned_openapi(spec) {
            Ok(spec) => return Ok(spec.into()),
            Err(err) => errors.push(err),
        },
        Err(err) => errors.push(err),
    };

    match serde_json::from_str::<VersionedOpenAPI>(&file_contents)
        .context("Failed to parse as JSON OpenAPI v2/v3.0")
    {
        Ok(spec) => match upgrade_versioned_openapi(spec) {
            Ok(spec) => return Ok(spec.into()),
            Err(err) => errors.push(err),
        },
        Err(err) => errors.push(err),
    };

    // The strategies above cover the vast majority of well-formed specs, but
    // some real-world documents in the wild are rejected by both `oas3` and
    // `openapiv3`, for example because they use a Swagger 2.0 construct that
    // isn't supported by those crates (`in: formData` parameters), or contain
    // a literal duplicate object key that `serde_yaml`'s `Value` refuses to
    // merge. `roas` is an independent OpenAPI implementation that is more
    // permissive in some of these cases, so we try it as a last resort.
    //
    // We also retry against a "deduplicated" rendition of the file (parsed
    // generically as JSON and re-serialized, which keeps the last of any
    // duplicate keys) since `roas`'s own strict deserializer, like `serde_yaml`'s,
    // refuses documents with duplicate keys.
    match roas_from_str(&file_contents).context("Failed to parse using roas") {
        Ok(spec) => return Ok(spec),
        Err(err) => errors.push(err),
    }
    if let Some(deduped) = dedupe_json_object_keys(&file_contents) {
        match roas_from_str(&deduped)
            .context("Failed to parse using roas (after deduplicating JSON object keys)")
        {
            Ok(spec) => return Ok(spec),
            Err(err) => errors.push(err),
        }
    }

    // Some Swagger 2.0 documents in the wild use schema constructs that none
    // of the crates above model correctly: a non-standard `type: file` (valid
    // only on `body`/`formData` parameters in Swagger 2.0, to indicate a file
    // upload) and integer `format`s other than `int32`/`int64` (e.g. `uint32`,
    // `int8`), which `roas`'s Swagger 2.0 model restricts to a closed enum.
    // Neither affects fuzzing behaviour, so as a last resort we generically
    // rewrite `type: file` to the OpenAPI 3.0-style `{type: string, format:
    // binary}`, and drop non-standard integer `format`s, wherever they occur
    // in the document, and retry.
    if let Some(sanitized) = sanitize_legacy_schema_quirks(&file_contents) {
        match roas_from_str(&sanitized)
            .context("Failed to parse using roas (after normalizing legacy schema constructs)")
        {
            Ok(spec) => return Ok(spec),
            Err(err) => errors.push(err),
        }
        if let Some(deduped) = dedupe_json_object_keys(&sanitized) {
            match roas_from_str(&deduped).context(
                "Failed to parse using roas (after normalizing legacy schema constructs and deduplicating JSON object keys)",
            ) {
                Ok(spec) => return Ok(spec),
                Err(err) => errors.push(err),
            }
        }
    }

    Err(AttemptsFailed { errors }.into())
}

/// Upgrades a parsed `VersionedOpenAPI` (v2 or v3.0) document to v3.0, via
/// `openapiv3-extended`'s own `upgrade()` method.
///
/// `upgrade()` is not panic-safe: it `panic!`s (rather than returning a
/// `Result`) on some non-standard-but-real-world Swagger 2.0 constructs, for
/// example schema properties using the non-standard `type: file` (seen in
/// `proxyprint.json` from the WebFuzzing/Dataset benchmark). Since this is
/// just one of several fallback strategies tried by `openapi_from_file`, a
/// panic here shouldn't take down the whole process: we catch it and turn it
/// into a regular error so later strategies (e.g. the `roas`-based ones,
/// combined with `sanitize_legacy_schema_quirks`) still get a chance to run.
fn upgrade_versioned_openapi(spec: VersionedOpenAPI) -> Result<openapiv3::OpenAPI> {
    // Suppress the default panic hook's stderr output for the duration of
    // the call: a caught panic here is an expected, handled fallback
    // failure, not something that should be logged as if it crashed.
    let previous_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| spec.upgrade()));
    std::panic::set_hook(previous_hook);

    result.map_err(|payload| {
        let message = payload
            .downcast_ref::<&str>()
            .map(|s| s.to_string())
            .or_else(|| payload.downcast_ref::<String>().cloned())
            .unwrap_or_else(|| "unknown panic".to_string());
        anyhow::anyhow!("panicked while upgrading OpenAPI v2/v3.0 document: {message}")
    })
}

/// Parses `file_contents` with the `roas` crate as OpenAPI v3.1, v3.0 or v2,
/// trying each version (and both JSON and YAML syntax) in turn, and converts
/// the result to our internal `Spec` representation.
///
/// `roas` models each OpenAPI version with its own, independent type, but
/// provides `From` conversions to upgrade a document to the next version
/// (v2 -> v3.0 -> v3.1). We parse whichever version succeeds first, upgrade
/// it to v3.1, and then convert it to our internal (`oas3`-based) `Spec` by
/// re-serializing it to JSON and parsing that with `oas3`. This piggybacks on
/// `oas3`'s already-tested v3.1 parsing and the existing `From<oas3::Spec>`
/// conversion, instead of hand-writing a second, parallel field-by-field
/// converter.
fn roas_from_str(file_contents: &str) -> Result<Spec> {
    fn convert(spec: roas::v3_1::spec::Spec) -> Result<Spec> {
        let json =
            serde_json::to_string(&spec).context("Failed to re-serialize roas spec as JSON")?;
        oas3::from_json(&json)
            .map(Into::into)
            .context("Failed to parse roas-normalized spec with oas3")
    }

    if let Ok(spec) = serde_json::from_str::<roas::v3_1::spec::Spec>(file_contents) {
        return convert(spec);
    }
    if let Ok(spec) = serde_yaml::from_str::<roas::v3_1::spec::Spec>(file_contents) {
        return convert(spec);
    }
    if let Ok(spec) = serde_json::from_str::<roas::v3_0::spec::Spec>(file_contents) {
        return convert(spec.into());
    }
    if let Ok(spec) = serde_yaml::from_str::<roas::v3_0::spec::Spec>(file_contents) {
        return convert(spec.into());
    }
    if let Ok(spec) = serde_json::from_str::<roas::v2::spec::Spec>(file_contents) {
        let v3_0: roas::v3_0::spec::Spec = spec.into();
        return convert(v3_0.into());
    }
    if let Ok(spec) = serde_yaml::from_str::<roas::v2::spec::Spec>(file_contents) {
        let v3_0: roas::v3_0::spec::Spec = spec.into();
        return convert(v3_0.into());
    }

    anyhow::bail!("Did not match any supported OpenAPI version (v3.1, v3.0 or v2) in JSON or YAML")
}

/// Parses `contents` as generic JSON and re-serializes it. Object keys that
/// occur more than once within the same object are merged, keeping only the
/// last occurrence, in line with the behaviour of most lenient JSON parsers
/// (and the JSON specification's recommendation). Returns `None` if `contents`
/// isn't valid generic JSON (e.g. because it is YAML, or is empty).
///
/// This is only used as a last-resort retry (see `openapi_from_file`), after
/// all other strategies -- including `roas` on the untouched file -- have
/// already failed, so we don't bother checking whether deduplication actually
/// changed anything before retrying.
fn dedupe_json_object_keys(contents: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(contents).ok()?;
    serde_json::to_string(&value).ok()
}

/// Generically rewrites two Swagger 2.0 JSON-Schema constructs that aren't
/// recognized by our parsing crates, wherever they occur anywhere in the
/// document, and returns the re-serialized document if anything was changed
/// (or `None` if the document couldn't be parsed generically, or nothing
/// needed patching):
///
/// - A schema's non-standard `type: file` (valid only on Swagger 2.0 `body`/
///   `formData` parameters, to indicate a file upload) is rewritten to the
///   OpenAPI 3.0-style equivalent, `{type: string, format: binary}`.
/// - An integer schema's `format`, if it is anything other than the two
///   standard values `int32`/`int64` (e.g. `uint32`, `int8`, as seen in the
///   wild), is dropped. `format` is purely descriptive/advisory for fuzzing
///   purposes, so losing it is harmless, whereas keeping it causes some
///   parsers (which model `format` as a closed enum for Swagger 2.0) to
///   reject the whole document.
fn sanitize_legacy_schema_quirks(contents: &str) -> Option<String> {
    let mut doc = serde_yaml::from_str::<serde_yaml::Value>(contents).ok()?;
    let mut changed = false;
    fix_legacy_schema_quirks(&mut doc, &mut changed);
    changed.then(|| serde_yaml::to_string(&doc).ok()).flatten()
}

/// Recursively walks `value`, applying the schema fixes described on
/// `sanitize_legacy_schema_quirks`, and sets `changed` to `true` if anything
/// was rewritten.
fn fix_legacy_schema_quirks(value: &mut serde_yaml::Value, changed: &mut bool) {
    if let serde_yaml::Value::Mapping(map) = value {
        let type_key = serde_yaml::Value::String("type".to_string());
        let format_key = serde_yaml::Value::String("format".to_string());

        match map.get(&type_key).cloned() {
            Some(serde_yaml::Value::String(t)) if t == "file" => {
                map.insert(type_key, serde_yaml::Value::String("string".to_string()));
                map.insert(format_key, serde_yaml::Value::String("binary".to_string()));
                *changed = true;
            }
            Some(serde_yaml::Value::String(t)) if t == "integer" => {
                if let Some(serde_yaml::Value::String(f)) = map.get(&format_key).cloned()
                    && f != "int32"
                    && f != "int64"
                {
                    map.remove(&format_key);
                    *changed = true;
                }
            }
            _ => {}
        }

        for (_, v) in map.iter_mut() {
            fix_legacy_schema_quirks(v, changed);
        }
    } else if let serde_yaml::Value::Sequence(seq) = value {
        for v in seq.iter_mut() {
            fix_legacy_schema_quirks(v, changed);
        }
    }
}

/// Loads the OpenAPI specification from the given path
pub fn get_api_spec(path: &Path) -> Result<Box<Spec>, anyhow::Error> {
    openapi_from_file(path)
        .map(Box::new)
        .with_context(|| format!("Error parsing OpenAPI-file at {}", path.to_string_lossy()))
}

#[cfg(test)]
mod tests {
    use std::io::Write;

    use tempfile::NamedTempFile;

    use super::*;

    /// Helper: write `contents` to a temp file and load it via `openapi_from_file`.
    fn load_spec_from_str(contents: &str) -> Spec {
        let mut file = NamedTempFile::new().unwrap();
        file.write_all(contents.as_bytes()).unwrap();
        openapi_from_file(file.path()).expect("Failed to load spec")
    }

    fn schema_object(schema: &oas3::spec::Schema) -> &oas3::spec::ObjectSchema {
        match schema {
            oas3::spec::Schema::Boolean(_) => panic!("Expected object schema, got boolean schema"),
            oas3::spec::Schema::Object(schema_ref) => match schema_ref.as_ref() {
                oas3::spec::ObjectOrReference::Object(schema) => schema,
                oas3::spec::ObjectOrReference::Ref { .. } => {
                    panic!("Expected concrete schema, got $ref")
                }
            },
        }
    }

    /// Helper: given a loaded Spec, find the schema for a given component name.
    fn get_component_schema<'a>(spec: &'a Spec, name: &str) -> &'a oas3::spec::ObjectSchema {
        let components = spec.components.as_ref().expect("spec has no components");
        schema_object(components.schemas.get(name).expect("schema not found"))
    }

    /// Regression test for specs with a completely empty `info: {}` object
    /// (e.g. bibliothek.json from the WebFuzzing/Dataset benchmark), which
    /// would otherwise fail to parse with "missing field `title`"/"missing
    /// field `version`" under every parsing strategy.
    #[test]
    fn empty_info_object_gets_placeholder_title_and_version() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.1",
                "info": {},
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, DEFAULT_INFO_TITLE);
        assert_eq!(spec.info.version, DEFAULT_INFO_VERSION);
    }

    /// Regression test for specs missing the `info` key entirely (e.g.
    /// blogapi.json-style documents).
    #[test]
    fn missing_info_key_gets_placeholder_title_and_version() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, DEFAULT_INFO_TITLE);
        assert_eq!(spec.info.version, DEFAULT_INFO_VERSION);
    }

    /// A spec with only `title` missing should keep the existing `version`;
    /// only the missing field gets a placeholder.
    #[test]
    fn only_missing_field_is_patched() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "info": { "version": "4.2.0" },
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, DEFAULT_INFO_TITLE);
        assert_eq!(spec.info.version, "4.2.0");
    }

    /// A fully valid spec must be loaded completely unaffected: no placeholder
    /// substitution should occur when `info.title`/`info.version` are present.
    #[test]
    fn well_formed_info_is_left_untouched() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "info": { "title": "My API", "version": "1.2.3" },
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, "My API");
        assert_eq!(spec.info.version, "1.2.3");
    }

    /// Verifies that schema-level `example` (singular, v3.0 keyword) is preserved
    /// across all schema types when loaded via the oas3 path (v3.0 YAML).
    /// The oas3 library stores v3.0's singular `example` in the deprecated `example` field,
    /// not in the v3.1 `examples` Vec.
    #[test]
    fn upgrade_preserves_schema_examples_all_types() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths: {}
components:
  schemas:
    Greeting:
      type: string
      example: "Hello, world!"
    Age:
      type: integer
      example: 42
    Tags:
      type: array
      items:
        type: string
      example: ["alpha", "beta"]
    User:
      type: object
      properties:
        name:
          type: string
          example: "nested@example.com"
        age:
          type: integer
      example:
        name: Alice
        age: 30
"#;
        let spec = load_spec_from_str(spec_yaml);

        // oas3 stores v3.0's singular `example` in the `example` field (deprecated but functional)
        let greeting = get_component_schema(&spec, "Greeting");
        assert_eq!(
            greeting.example,
            Some(serde_json::json!("Hello, world!")),
            "String example lost. example: {:?}",
            greeting.example
        );

        let age = get_component_schema(&spec, "Age");
        assert_eq!(
            age.example,
            Some(serde_json::json!(42)),
            "Integer example lost. example: {:?}",
            age.example
        );

        let tags = get_component_schema(&spec, "Tags");
        assert_eq!(
            tags.example,
            Some(serde_json::json!(["alpha", "beta"])),
            "Array example lost. example: {:?}",
            tags.example
        );

        let user = get_component_schema(&spec, "User");
        assert_eq!(
            user.example,
            Some(serde_json::json!({"name": "Alice", "age": 30})),
            "Object example lost. example: {:?}",
            user.example
        );

        // Nested property example
        let name_schema = schema_object(user.properties.get("name").unwrap());
        assert_eq!(
            name_schema.example,
            Some(serde_json::json!("nested@example.com")),
            "Nested property example lost. example: {:?}",
            name_schema.example
        );
    }

    /// Verifies that MediaType-level examples (on request bodies) are preserved.
    #[test]
    fn upgrade_preserves_media_type_example() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths:
  /items:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example:
              name: "TestItem"
      responses:
        '200':
          description: OK
"#;
        let spec = load_spec_from_str(spec_yaml);
        let operation = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/items")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        let request_body = operation
            .request_body
            .as_ref()
            .unwrap()
            .resolve(&spec)
            .expect("could not resolve request body");
        let media_type = request_body
            .content
            .get("application/json")
            .expect("missing application/json content");
        match &media_type.examples {
            Some(oas3::spec::MediaTypeExamples::Example { example }) => {
                assert_eq!(*example, serde_json::json!({"name": "TestItem"}));
            }
            other => panic!("Expected MediaTypeExamples::Example, got {:?}", other),
        }
    }

    /// Verifies that a v3.1 spec with `examples` (plural, array form) is loaded correctly.
    #[test]
    fn v31_spec_preserves_schema_examples() {
        let spec_yaml = r#"
openapi: "3.1.0"
info:
  title: Test
  version: "1.0"
paths: {}
components:
  schemas:
    Color:
      type: string
      examples:
        - "red"
        - "green"
        - "blue"
"#;
        let spec = load_spec_from_str(spec_yaml);
        let schema = get_component_schema(&spec, "Color");
        assert!(schema.examples.contains(&serde_json::json!("red")));
        assert!(schema.examples.contains(&serde_json::json!("blue")));
    }

    /// Verifies that `example` on composition schemas (allOf/oneOf/anyOf) is preserved
    /// when going through the openapiv3 upgrade path (Swagger 2.0 forces this path).
    #[test]
    fn upgrade_preserves_example_on_composition_schemas() {
        let spec_json = r#"{
  "swagger": "2.0",
  "info": { "title": "Test", "version": "1.0" },
  "host": "localhost",
  "basePath": "/",
  "paths": {},
  "definitions": {
    "Pet": {
      "allOf": [
        { "type": "object", "properties": { "name": { "type": "string" } } },
        { "type": "object", "properties": { "age": { "type": "integer" } } }
      ],
      "example": { "name": "Fido", "age": 5 }
    },
    "Shape": {
      "oneOf": [
        { "type": "object", "properties": { "radius": { "type": "number" } } },
        { "type": "object", "properties": { "width": { "type": "number" } } }
      ],
      "example": { "radius": 1.4 }
    },
    "Flexible": {
      "anyOf": [
        { "type": "string" },
        { "type": "integer" }
      ],
      "example": "hello"
    }
  }
}"#;
        let spec = load_spec_from_str(spec_json);

        let pet = get_component_schema(&spec, "Pet");
        assert!(
            pet.examples
                .contains(&serde_json::json!({"name": "Fido", "age": 5})),
            "allOf example lost. examples: {:?}",
            pet.examples
        );

        let shape = get_component_schema(&spec, "Shape");
        assert!(
            shape.examples.contains(&serde_json::json!({"radius": 1.4})),
            "oneOf example lost. examples: {:?}",
            shape.examples
        );

        let flexible = get_component_schema(&spec, "Flexible");
        assert!(
            flexible.examples.contains(&serde_json::json!("hello")),
            "anyOf example lost. examples: {:?}",
            flexible.examples
        );
    }

    /// Verifies that parameter-level `example` and parameter schema `example`
    /// are both preserved (v3.0, oas3 path).
    #[test]
    fn upgrade_preserves_parameter_examples() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths:
  /users/{userId}:
    get:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            example: 123
          example: 456
      responses:
        '200':
          description: OK
"#;
        let spec = load_spec_from_str(spec_yaml);
        let operation = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/users/{userId}")
            .unwrap()
            .get
            .as_ref()
            .unwrap();
        let param = operation
            .parameters
            .iter()
            .filter_map(|p| p.resolve(&spec).ok())
            .find(|p| p.name == "userId")
            .expect("userId parameter missing");

        // Parameter-level example (on the Parameter object itself)
        assert_eq!(
            param.example,
            Some(serde_json::json!(456)),
            "Parameter-level example lost"
        );

        // Schema-level example (nested inside the parameter's schema)
        // oas3 stores v3.0's singular `example` in the deprecated `example` field
        let schema = match &param.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on parameter"),
        };
        assert_eq!(
            schema.example,
            Some(serde_json::json!(123)),
            "Parameter schema example lost. example: {:?}",
            schema.example
        );
    }

    /// Verifies that schema examples survive the openapiv3 upgrade path with
    /// deeply nested properties (Swagger 2.0 forces this path).
    #[test]
    fn upgrade_from_swagger2_preserves_schema_examples() {
        let spec_json = r#"{
  "swagger": "2.0",
  "info": { "title": "Test", "version": "1.0" },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/search": {
      "post": {
        "parameters": [{
          "name": "body",
          "in": "body",
          "schema": {
            "type": "object",
            "properties": {
              "query": { "type": "string", "example": "search term" },
              "options": {
                "type": "object",
                "properties": {
                  "limit": { "type": "integer", "example": 50 }
                },
                "example": { "limit": 50 }
              }
            },
            "example": { "query": "test", "options": { "limit": 25 } }
          }
        }],
        "responses": { "200": { "description": "OK" } }
      }
    }
  },
  "definitions": {
    "Status": { "type": "string", "example": "active" }
  }
}"#;
        let spec = load_spec_from_str(spec_json);

        // Component schema example
        let status = get_component_schema(&spec, "Status");
        assert!(
            status.examples.contains(&serde_json::json!("active")),
            "Component schema example lost. examples: {:?}",
            status.examples
        );

        // Body schema (top-level) - The v2 upgrade wraps body params in an object,
        // so the actual schema is nested as a property named "body".
        let operation = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/search")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        let body = operation
            .request_body
            .as_ref()
            .unwrap()
            .resolve(&spec)
            .expect("could not resolve body");
        let wrapper_schema = match &body.content.iter().next().unwrap().1.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on request body"),
        };
        let body_schema = schema_object(wrapper_schema.properties.get("body").unwrap());
        assert!(
            body_schema
                .examples
                .contains(&serde_json::json!({"query": "test", "options": {"limit": 25}})),
            "Body schema example lost. examples: {:?}",
            body_schema.examples
        );

        // Nested property example
        let query_prop = schema_object(body_schema.properties.get("query").unwrap());
        assert!(
            query_prop
                .examples
                .contains(&serde_json::json!("search term")),
            "Nested property example lost. examples: {:?}",
            query_prop.examples
        );

        // Deeply nested property example (options.limit)
        let options_prop = schema_object(body_schema.properties.get("options").unwrap());
        let limit_prop = schema_object(options_prop.properties.get("limit").unwrap());
        assert!(
            limit_prop.examples.contains(&serde_json::json!(50)),
            "Deeply nested example lost. examples: {:?}",
            limit_prop.examples
        );
    }

    /// Compares loading a v3.0 spec via the oas3 path (direct) vs the openapiv3 path
    /// (upgrade). Both paths should produce the same schema data. If they diverge,
    /// it indicates one path is losing data that the other preserves.
    #[test]
    fn v30_oas3_vs_openapiv3_paths_produce_same_schema_data() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths:
  /items/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 7
          example: 42
      responses:
        '200':
          description: OK
components:
  schemas:
    Item:
      type: object
      title: "An Item"
      description: "Represents an item in the store"
      default: { "name": "unnamed", "price": 0 }
      example: { "name": "Widget", "price": 9.99 }
      properties:
        name:
          type: string
          title: "Item name"
          example: "Gadget"
        price:
          type: number
          example: 4.99
    Status:
      type: string
      example: "active"
      default: "pending"
"#;
        // Path 1: oas3 directly (what openapi_from_file does for v3.0)
        let spec_via_oas3: Spec = oas3::from_yaml(spec_yaml)
            .expect("oas3 should parse v3.0")
            .into();

        // Path 2: openapiv3 parse + upgrade (what would happen if oas3 rejected it)
        let spec_via_openapiv3: Spec = serde_yaml::from_str::<VersionedOpenAPI>(spec_yaml)
            .expect("openapiv3 should parse v3.0")
            .upgrade()
            .into();

        // Compare component schemas
        let oas3_components = spec_via_oas3.components.as_ref().unwrap();
        let openapiv3_components = spec_via_openapiv3.components.as_ref().unwrap();

        for schema_name in ["Item", "Status"] {
            let oas3_schema = schema_object(oas3_components.schemas.get(schema_name).unwrap());
            let openapiv3_schema =
                schema_object(openapiv3_components.schemas.get(schema_name).unwrap());

            // oas3 path stores v3.0's singular `example` in deprecated `example` field,
            // openapiv3 conversion stores it in the v3.1 `examples` Vec.
            // Verify both paths preserve the example data (just in different fields).
            let oas3_example = oas3_schema.example.clone();
            let openapiv3_examples = &openapiv3_schema.examples;
            if let Some(ex) = &oas3_example {
                assert!(
                    openapiv3_examples.contains(ex),
                    "Schema '{schema_name}': oas3 has example={:?} but openapiv3 examples={:?}",
                    oas3_example,
                    openapiv3_examples
                );
            }
            assert_eq!(
                oas3_schema.title, openapiv3_schema.title,
                "Schema '{schema_name}' title differs between paths"
            );
            assert_eq!(
                oas3_schema.description, openapiv3_schema.description,
                "Schema '{schema_name}' description differs between paths"
            );
            assert_eq!(
                oas3_schema.default, openapiv3_schema.default,
                "Schema '{schema_name}' default differs between paths"
            );
        }

        // Compare nested property schemas
        let oas3_item = schema_object(oas3_components.schemas.get("Item").unwrap());
        let openapiv3_item = schema_object(openapiv3_components.schemas.get("Item").unwrap());
        for prop_name in ["name", "price"] {
            let oas3_prop = schema_object(oas3_item.properties.get(prop_name).unwrap());
            let openapiv3_prop = schema_object(openapiv3_item.properties.get(prop_name).unwrap());
            let oas3_example = oas3_prop.example.clone();
            let openapiv3_examples = &openapiv3_prop.examples;
            if let Some(ex) = &oas3_example {
                assert!(
                    openapiv3_examples.contains(ex),
                    "Property '{prop_name}': oas3 has example={:?} but openapiv3 examples={:?}",
                    oas3_example,
                    openapiv3_examples
                );
            }
            assert_eq!(
                oas3_prop.title, openapiv3_prop.title,
                "Property '{prop_name}' title differs between paths"
            );
        }

        // Compare parameter data
        let oas3_param = spec_via_oas3
            .paths
            .as_ref()
            .into_iter()
            .flat_map(|map| map.get("/items/{id}"))
            .flat_map(|path_item| path_item.get.as_ref())
            .flat_map(|op| op.parameters.iter())
            .filter_map(|p| p.resolve(&spec_via_oas3).ok())
            .find(|p| p.name == "id")
            .unwrap();
        let openapiv3_param = spec_via_openapiv3
            .paths
            .as_ref()
            .into_iter()
            .flat_map(|map| map.get("/items/{id}"))
            .flat_map(|path_item| path_item.get.as_ref())
            .flat_map(|op| op.parameters.iter())
            .filter_map(|p| p.resolve(&spec_via_openapiv3).ok())
            .find(|p| p.name == "id")
            .unwrap();

        assert_eq!(
            oas3_param.example, openapiv3_param.example,
            "Parameter 'id' example differs.\n  oas3: {:?}\n  openapiv3: {:?}",
            oas3_param.example, openapiv3_param.example
        );
        let oas3_param_schema = match &oas3_param.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on id param in oas3 path"),
        };
        let openapiv3_param_schema = match &openapiv3_param.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on id param in openapiv3 path"),
        };
        let oas3_param_example = oas3_param_schema.example.clone();
        let openapiv3_param_examples = &openapiv3_param_schema.examples;
        if let Some(ex) = &oas3_param_example {
            assert!(
                openapiv3_param_examples.contains(ex),
                "Parameter schema: oas3 has example={:?} but openapiv3 examples={:?}",
                oas3_param_example,
                openapiv3_param_examples
            );
        }
    }

    /// Regression test for Swagger 2.0 specs using `in: formData` parameters
    /// (e.g. languagetool.json from the WebFuzzing/Dataset benchmark), which
    /// neither `oas3` nor `openapiv3`'s v2 support can deserialize (`formData`
    /// isn't a valid v2 parameter location in those crates' models), but
    /// `roas`'s v2 model handles natively.
    #[test]
    fn swagger2_form_data_parameter_is_parsed_via_roas() {
        let spec = load_spec_from_str(
            r#"{
                "swagger": "2.0",
                "info": { "title": "Form data API", "version": "1.0" },
                "paths": {
                    "/check": {
                        "post": {
                            "operationId": "check",
                            "parameters": [
                                {
                                    "name": "text",
                                    "in": "formData",
                                    "type": "string",
                                    "required": false
                                }
                            ],
                            "responses": { "200": { "description": "OK" } }
                        }
                    }
                }
            }"#,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/check")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("check"));
    }

    /// Regression test for specs with a literal duplicate object key within
    /// the same path item (e.g. two `"get"` entries under `/api/albums` in
    /// blogapi.json from the WebFuzzing/Dataset benchmark). `serde_yaml`'s
    /// generic `Value` (used by our own pre-processing) and `roas`'s strict
    /// deserializer both reject such documents outright, so we retry through
    /// a generic `serde_json::Value` round-trip first, which keeps only the
    /// last occurrence of a duplicate key, matching how most lenient JSON
    /// parsers behave.
    ///
    /// This test also uses a boolean `exclusiveMinimum` (valid OpenAPI 3.0 /
    /// JSON Schema draft-4 syntax, as opposed to v3.1's numeric form), to
    /// verify that `roas`'s v3.0 -> v3.1 upgrade correctly translates it.
    #[test]
    fn duplicate_path_item_key_is_resolved_via_last_value() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "info": { "title": "Duplicate key API", "version": "1.0" },
                "paths": {
                    "/api/albums": {
                        "get": {
                            "operationId": "broken_stub",
                            "responses": { "200": { "description": "stub, should be discarded" } }
                        },
                        "get": {
                            "operationId": "real_operation",
                            "parameters": [
                                {
                                    "name": "page",
                                    "in": "query",
                                    "required": false,
                                    "schema": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "exclusiveMinimum": false
                                    }
                                }
                            ],
                            "responses": { "200": { "description": "OK" } }
                        }
                    }
                }
            }"#,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/api/albums")
            .unwrap()
            .get
            .as_ref()
            .unwrap();
        // The last of the two duplicate `get` keys should win.
        assert_eq!(op.operation_id.as_deref(), Some("real_operation"));
    }

    #[test]
    fn dedupe_json_object_keys_keeps_last_occurrence() {
        let deduped = dedupe_json_object_keys(
            r#"{"a": 1, "nested": {"x": "stub"}, "nested": {"x": "real"}}"#,
        )
        .expect("should be valid JSON");
        let value: serde_json::Value = serde_json::from_str(&deduped).unwrap();
        assert_eq!(value["nested"]["x"], "real");
    }

    #[test]
    fn dedupe_json_object_keys_returns_none_for_yaml() {
        // Plain YAML (not valid as generic JSON) should be rejected, not panic.
        assert!(dedupe_json_object_keys("openapi: 3.0.0\ninfo:\n  title: x\n").is_none());
    }

    /// Regression test for Swagger 2.0's non-standard `type: file` schema
    /// (valid only on `body`/`formData` parameters, to indicate a file
    /// upload, e.g. in proxyprint.json from the WebFuzzing/Dataset
    /// benchmark), which `roas`'s Swagger 2.0 schema model rejects outright
    /// (it only recognizes `type: object` in that position).
    #[test]
    fn swagger2_file_type_parameter_is_parsed_via_roas() {
        // `type: file` used as a *schema property* type (as opposed to a
        // `formData` parameter's own `type`, which `roas` already supports
        // natively) is a non-standard Swagger 2.0 construct seen in
        // `proxyprint.json` from the WebFuzzing/Dataset benchmark: `roas`'s
        // schema model has no `file` variant, so this only parses after
        // `sanitize_legacy_schema_quirks` rewrites it to the OAS3-equivalent
        // `{type: string, format: binary}`.
        let spec = load_spec_from_str(
            r##"{
                "swagger": "2.0",
                "info": { "title": "File upload API", "version": "1.0" },
                "paths": {
                    "/upload": {
                        "post": {
                            "operationId": "upload",
                            "responses": {
                                "200": {
                                    "description": "OK",
                                    "schema": { "$ref": "#/definitions/FileResource" }
                                }
                            }
                        }
                    }
                },
                "definitions": {
                    "FileResource": {
                        "type": "object",
                        "properties": {
                            "file": { "type": "file" }
                        }
                    }
                }
            }"##,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/upload")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("upload"));
    }

    /// Regression test for non-standard integer `format`s (e.g. `uint32`, as
    /// seen in youtube-mock.yaml from the WebFuzzing/Dataset benchmark), which
    /// `roas`'s Swagger 2.0 schema model restricts to a closed `int32`/`int64`
    /// enum.
    #[test]
    fn non_standard_integer_format_is_parsed_via_roas() {
        // `externalDocs` as a single object (rather than a list) at the
        // document root is valid Swagger 2.0, but trips up a bug in the
        // `openapiv3-extended` crate's v2 model (it expects a list there),
        // forcing a fall-through to the `roas`-based strategies below --
        // mirroring the real-world `youtube-mock.yaml` spec that surfaced
        // this combination of quirks.
        let spec = load_spec_from_str(
            r#"{
                "swagger": "2.0",
                "info": { "title": "Odd format API", "version": "1.0" },
                "externalDocs": { "url": "https://example.com" },
                "paths": {
                    "/count": {
                        "get": {
                            "operationId": "count",
                            "responses": {
                                "200": {
                                    "description": "OK",
                                    "schema": { "type": "integer", "format": "uint32" }
                                }
                            }
                        }
                    }
                }
            }"#,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/count")
            .unwrap()
            .get
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("count"));
    }

    #[test]
    fn sanitize_legacy_schema_quirks_rewrites_file_type() {
        let sanitized =
            sanitize_legacy_schema_quirks(r#"{"type": "file", "description": "upload"}"#)
                .expect("should have changed something");
        let value: serde_yaml::Value = serde_yaml::from_str(&sanitized).unwrap();
        assert_eq!(value["type"], serde_yaml::Value::String("string".into()));
        assert_eq!(value["format"], serde_yaml::Value::String("binary".into()));
    }

    #[test]
    fn sanitize_legacy_schema_quirks_drops_non_standard_integer_format() {
        let sanitized = sanitize_legacy_schema_quirks(r#"{"type": "integer", "format": "uint32"}"#)
            .expect("should have changed something");
        let value: serde_yaml::Value = serde_yaml::from_str(&sanitized).unwrap();
        assert!(value.get("format").is_none());
    }

    #[test]
    fn sanitize_legacy_schema_quirks_leaves_standard_schemas_untouched() {
        assert!(
            sanitize_legacy_schema_quirks(r#"{"type": "integer", "format": "int32"}"#).is_none()
        );
        assert!(sanitize_legacy_schema_quirks(r#"{"type": "string"}"#).is_none());
    }
}
