//! Loads an OpenAPI specification from a file, and converts it to the format we use.

use std::{cell::RefCell, collections::HashSet, path::Path};

use anyhow::{Context, Result};
use openapiv3::VersionedOpenAPI;
use serde::de::{DeserializeSeed, MapAccess, SeqAccess, Visitor};

use super::Spec;

/// AttemptsFailed records a parallel set of errors, that result from multiple
/// strategies failing. When Displayed, it prints all error chains that resulted
/// from the different attempts, so the user can find the strategy they wanted
/// to use and fix the errors that resulted in that attempt.
#[derive(Debug)]
struct AttemptsFailed {
    errors: Vec<anyhow::Error>,
}

impl std::fmt::Display for AttemptsFailed {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (i, err) in self.errors.iter().enumerate() {
            writeln!(f, "{i}. {err}")?;
            for cause in err.chain().skip(1) {
                writeln!(f, "     because: {cause}")?;
            }
        }
        Ok(())
    }
}

impl std::error::Error for AttemptsFailed {}

/// Placeholder used when a spec's `info.title` is missing, null, or empty.
/// Used only to make the spec parseable; not used for fuzzing.
const DEFAULT_INFO_TITLE: &str = "Untitled API";

/// Placeholder used when a spec's `info.version` is missing, null, or empty.
/// Used only to make the spec parseable; not used for fuzzing.
const DEFAULT_INFO_VERSION: &str = "0.0.0";

/// Some real-world OpenAPI specs (e.g. generated by springdoc-openapi) omit
/// `info.title`/`info.version`, or leave them blank, even though both are
/// required fields in the OpenAPI specification. All of our parsing
/// strategies therefore reject them outright with an unhelpful "missing field
/// `title`" error, even though these fields are irrelevant to fuzzing.
///
/// This patches the raw file contents (parsed generically, so it works for
/// both JSON and YAML input) by inserting placeholder values for any missing,
/// null, or empty `info.title`/`info.version` fields, logging a warning for
/// each one patched. If both fields are already present and non-empty, the
/// original `contents` is returned completely unchanged.
fn fill_in_missing_info_fields(contents: &str, filename: &Path) -> String {
    let Ok(mut doc) = serde_yaml::from_str::<serde_yaml::Value>(contents) else {
        // Not parseable even generically; let the real parsing attempts
        // further down produce the actual error message.
        return contents.to_string();
    };

    let is_blank = |value: Option<&serde_yaml::Value>| match value {
        None | Some(serde_yaml::Value::Null) => true,
        Some(serde_yaml::Value::String(s)) => s.is_empty(),
        _ => false,
    };

    let Some(mapping) = doc.as_mapping_mut() else {
        return contents.to_string();
    };

    let info = mapping
        .entry(serde_yaml::Value::String("info".to_string()))
        .or_insert_with(|| serde_yaml::Value::Mapping(Default::default()));
    let Some(info) = info.as_mapping_mut() else {
        return contents.to_string();
    };

    let mut patched = false;
    for (field, default) in [
        ("title", DEFAULT_INFO_TITLE),
        ("version", DEFAULT_INFO_VERSION),
    ] {
        let key = serde_yaml::Value::String(field.to_string());
        if is_blank(info.get(&key)) {
            log::warn!(
                "OpenAPI spec at {} is missing info.{field}; using placeholder value {default:?}",
                filename.to_string_lossy()
            );
            info.insert(key, serde_yaml::Value::String(default.to_string()));
            patched = true;
        }
    }

    if !patched {
        return contents.to_string();
    }
    serde_yaml::to_string(&doc).unwrap_or_else(|_| contents.to_string())
}

pub fn openapi_from_file(filename: &Path) -> Result<Spec> {
    let file_contents = std::fs::read_to_string(filename)?;
    let file_contents = fill_in_missing_info_fields(&file_contents, filename);
    let mut errors = Vec::new();

    // Tries one parsing strategy, expressed as a `Result<Spec>` thunk (so
    // each call site can freely chain `.context(...)`/`.and_then(...)`/
    // `.map(...)` to build up its own `Result<Spec>` before handing it over
    // here). On success, returns the spec for the caller to return
    // immediately; on failure, records the error and returns `None` so the
    // caller falls through to the next strategy.
    let mut try_strategy = |result: Result<Spec>| -> Option<Spec> {
        match result {
            Ok(spec) => Some(spec),
            Err(err) => {
                errors.push(err);
                None
            }
        }
    };

    if let Some(spec) = try_strategy(
        oas3::from_yaml(&file_contents)
            .map(Into::into)
            .context("Failed to parse as YAML OpenAPI v3.1"),
    ) {
        return Ok(spec);
    }
    if let Some(spec) = try_strategy(
        oas3::from_json(&file_contents)
            .map(Into::into)
            .context("Failed to parse as JSON OpenAPI v3.1"),
    ) {
        return Ok(spec);
    }
    if let Some(spec) = try_strategy(
        serde_yaml::from_str::<VersionedOpenAPI>(&file_contents)
            .context("Failed to parse as YAML OpenAPI v2/v3.0")
            .and_then(|spec| upgrade_versioned_openapi(spec, filename))
            .map(Into::into),
    ) {
        return Ok(spec);
    }
    if let Some(spec) = try_strategy(
        serde_json::from_str::<VersionedOpenAPI>(&file_contents)
            .context("Failed to parse as JSON OpenAPI v2/v3.0")
            .and_then(|spec| upgrade_versioned_openapi(spec, filename))
            .map(Into::into),
    ) {
        return Ok(spec);
    }

    // The strategies above cover the vast majority of well-formed specs, but
    // some real-world documents in the wild are rejected by both `oas3` and
    // `openapiv3`, for example because they use a Swagger 2.0 construct that
    // isn't supported by those crates (`in: formData` parameters), or contain
    // a literal duplicate object key that `serde_yaml`'s `Value` refuses to
    // merge. `roas` is an independent OpenAPI implementation that is more
    // permissive in some of these cases, so we try it as a last resort.
    //
    // We also retry against a "deduplicated" rendition of the file (parsed
    // generically as JSON and re-serialized, which keeps the last of any
    // duplicate keys) since `roas`'s own strict deserializer, like `serde_yaml`'s,
    // refuses documents with duplicate keys, and against a "sanitized"
    // rendition that rewrites a couple of other non-standard Swagger 2.0
    // schema constructs `roas` doesn't model (see `sanitize_legacy_schema_quirks`),
    // combining both when both apply.
    //
    // Reaching this point at all means the spec isn't fully standards-compliant
    // (every strategy above failed), so make sure the user finds out, even
    // though we recover from it automatically.
    log::warn!(
        "OpenAPI spec at {} could not be parsed as standard OpenAPI v3.2, v3.1, v3.0 or Swagger \
         v2; \
         retrying with more lenient fallback parsing. This does not affect fuzzing, but you may \
         want to validate the spec for standards compliance.",
        filename.to_string_lossy()
    );
    let mut try_roas = |contents: &str, context: &'static str| -> Option<Spec> {
        try_strategy(roas_from_str(contents, filename).context(context))
    };

    if let Some(spec) = try_roas(&file_contents, "Failed to parse using roas") {
        return Ok(spec);
    }
    if let Some(deduped) = dedupe_json_object_keys(&file_contents)
        && let Some(spec) = try_roas(
            &deduped,
            "Failed to parse using roas (after deduplicating JSON object keys)",
        )
    {
        warn_about_duplicate_keys(&file_contents, filename);
        return Ok(spec);
    }
    if let Some((sanitized, fixes)) = sanitize_legacy_schema_quirks(&file_contents) {
        if let Some(spec) = try_roas(
            &sanitized,
            "Failed to parse using roas (after normalizing legacy schema constructs)",
        ) {
            warn_about_schema_fixes(&fixes, filename);
            return Ok(spec);
        }
        if let Some(deduped) = dedupe_json_object_keys(&sanitized)
            && let Some(spec) = try_roas(
                &deduped,
                "Failed to parse using roas (after normalizing legacy schema constructs and \
                 deduplicating JSON object keys)",
            )
        {
            warn_about_schema_fixes(&fixes, filename);
            warn_about_duplicate_keys(&sanitized, filename);
            return Ok(spec);
        }
    }

    Err(AttemptsFailed { errors }.into())
}

/// Logs `header` followed by a bulleted (one per line, `  - `-prefixed) list
/// of `items`, if any. Does nothing if `items` is empty, so call sites don't
/// need to check that themselves.
fn warn_with_bullets<T: std::fmt::Display>(header: &str, items: &[T]) {
    if items.is_empty() {
        return;
    }
    log::warn!(
        "{header}\n{}",
        items
            .iter()
            .map(|item| format!("  - {item}"))
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Logs a warning listing every duplicate object key found in `contents`, if
/// any (see `find_duplicate_json_keys`). Called once we know deduplication
/// was actually necessary for `contents` to parse.
fn warn_about_duplicate_keys(contents: &str, filename: &Path) {
    warn_with_bullets(
        &format!(
            "OpenAPI spec at {} contains duplicate object keys; only the last occurrence of \
             each is used:",
            filename.to_string_lossy()
        ),
        &find_duplicate_json_keys(contents),
    );
}

/// Logs a warning listing every non-standard schema construct that
/// `sanitize_legacy_schema_quirks` had to rewrite, if any. Called once we know
/// sanitizing was actually necessary for the spec to parse.
fn warn_about_schema_fixes(fixes: &[String], filename: &Path) {
    warn_with_bullets(
        &format!(
            "OpenAPI spec at {} uses non-standard schema constructs that were automatically \
             rewritten to make it parseable:",
            filename.to_string_lossy()
        ),
        fixes,
    );
}

/// Upgrades a parsed `VersionedOpenAPI` (v2 or v3.0) document to v3.0, via
/// `openapiv3-extended`'s own `upgrade()` method.
///
/// `upgrade()` is not panic-safe: it `panic!`s (rather than returning a
/// `Result`) on some non-standard-but-real-world Swagger 2.0 constructs, for
/// example schema properties using the non-standard `type: file` (seen in
/// `proxyprint.json` from the WebFuzzing/Dataset benchmark). Since this is
/// just one of several fallback strategies tried by `openapi_from_file`, a
/// panic here shouldn't take down the whole process: we catch it, warn the
/// user (a panic here always indicates a non-standard spec, even if a later
/// strategy recovers), and turn it into a regular error so later strategies
/// (e.g. the `roas`-based ones, combined with `sanitize_legacy_schema_quirks`)
/// still get a chance to run.
fn upgrade_versioned_openapi(
    spec: VersionedOpenAPI,
    filename: &Path,
) -> Result<openapiv3::OpenAPI> {
    catch_panic(|| spec.upgrade()).map_err(|message| {
        log::warn!(
            "OpenAPI spec at {} uses a non-standard construct that crashed the Swagger/OpenAPI \
             2.0-3.0 parser ({message}); trying other parsing strategies.",
            filename.to_string_lossy()
        );
        anyhow::anyhow!("panicked while upgrading OpenAPI v2/v3.0 document: {message}")
    })
}

/// Runs `f`, returning the panic message instead of unwinding if it panics.
fn catch_panic<T>(f: impl FnOnce() -> T) -> std::result::Result<T, String> {
    // `std::panic::set_hook`/`take_hook` act on global, process-wide state,
    // so swapping the hook to suppress output for the duration of the call
    // below must be serialized against any other thread doing the same
    // (e.g. concurrent test runs, or future concurrent spec loading) to
    // avoid one thread permanently stealing another's hook.
    static HOOK_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    let _guard = HOOK_LOCK
        .lock()
        .unwrap_or_else(|poison| poison.into_inner());

    // Suppress the default panic hook's stderr output for the duration of
    // the call: a caught panic here is an expected, handled fallback
    // failure, not something that should be logged as if it crashed.
    let previous_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(f));
    std::panic::set_hook(previous_hook);

    result.map_err(|payload| {
        payload
            .downcast_ref::<&str>()
            .map(|s| s.to_string())
            .or_else(|| payload.downcast_ref::<String>().cloned())
            .unwrap_or_else(|| "unknown panic".to_string())
    })
}

/// Parses `file_contents` with the `roas` crate as OpenAPI v3.2, v3.1, v3.0
/// or v2, trying each version (and both JSON and YAML syntax) in turn, and
/// converts the result to our internal `Spec` representation.
///
/// `roas` models each OpenAPI version with its own, independent type, but
/// provides `From` conversions to upgrade a document to the next version
/// (v2 -> v3.0 -> v3.1 -> v3.2). We try the newest version first (since a
/// v3.2-only construct could otherwise be mis-parsed, and silently
/// misinterpreted, by an older version's more lenient/permissive model), then
/// fall back to older versions in turn. Whichever version matches is upgraded
/// to v3.2 and converted to our internal (`oas3`-based) `Spec` by
/// re-serializing it to JSON and parsing that with `oas3`. This piggybacks on
/// `oas3`'s already-tested JSON parsing and the existing `From<oas3::Spec>`
/// conversion, instead of hand-writing a second, parallel field-by-field
/// converter. (There is no `From<v3_2::Spec> for v3_1::Spec` conversion in
/// `roas`, since upgrades are one-directional, so a v3.2 document is
/// re-serialized and handed to `oas3` directly rather than being downgraded.)
fn roas_from_str(file_contents: &str, filename: &Path) -> Result<Spec> {
    fn convert<T: serde::Serialize>(spec: T) -> Result<Spec> {
        let json =
            serde_json::to_string(&spec).context("Failed to re-serialize roas spec as JSON")?;
        oas3::from_json(&json)
            .map(Into::into)
            .context("Failed to parse roas-normalized spec with oas3")
    }

    // Tries to parse `file_contents` as the given roas version `T` (JSON,
    // then YAML), and if either succeeds, warns about any semantic
    // validation issues and upgrades the parsed spec to v3.1 via `upgrade`
    // (the identity function if `T` already is `roas::v3_1::spec::Spec`) for
    // `convert`. Returns `None` (to let the caller try the next-older
    // version) if `T` doesn't match in either syntax.
    fn try_version<T, U>(
        file_contents: &str,
        filename: &Path,
        upgrade: impl FnOnce(T) -> U,
    ) -> Option<Result<Spec>>
    where
        T: serde::de::DeserializeOwned + roas::validation::Validate,
        U: serde::Serialize,
    {
        let spec = serde_json::from_str::<T>(file_contents)
            .ok()
            .or_else(|| serde_yaml::from_str::<T>(file_contents).ok())?;
        warn_about_roas_validation_issues(&spec, filename);
        // roas' version upgrades `expect` on some documents (e.g. a v2 response
        // without `description`).
        Some(
            catch_panic(|| upgrade(spec))
                .map_err(|message| {
                    log::warn!(
                        "OpenAPI spec at {} uses a non-standard construct that crashed the \
                         `roas` parser while upgrading to a newer OpenAPI version ({message}); \
                         trying other parsing strategies.",
                        filename.to_string_lossy()
                    );
                    anyhow::anyhow!("panicked while upgrading with roas: {message}")
                })
                .and_then(convert),
        )
    }

    try_version::<roas::v3_2::spec::Spec, _>(file_contents, filename, |spec| spec)
        .or_else(|| try_version::<roas::v3_1::spec::Spec, _>(file_contents, filename, |spec| spec))
        .or_else(|| {
            try_version::<roas::v3_0::spec::Spec, _>(
                file_contents,
                filename,
                Into::<roas::v3_1::spec::Spec>::into,
            )
        })
        .or_else(|| {
            try_version::<roas::v2::spec::Spec, _>(file_contents, filename, |spec| {
                let v3_0: roas::v3_0::spec::Spec = spec.into();
                Into::<roas::v3_1::spec::Spec>::into(v3_0)
            })
        })
        .unwrap_or_else(|| {
            anyhow::bail!(
                "Did not match any supported OpenAPI version (v3.2, v3.1, v3.0 or v2) in JSON or \
                 YAML"
            )
        })
}

/// Runs `roas`'s own semantic validator (distinct from, and in addition to,
/// the structural/syntax parsing `roas_from_str` already did to get here) on
/// a spec that only loaded at all via the lenient `roas` fallback cascade --
/// i.e. one we already know is non-standard in some way -- and logs any
/// findings so the user learns about *semantic* spec problems too (not just
/// the syntactic quirks `sanitize_legacy_schema_quirks`/`dedupe_json_object_keys`
/// work around), such as duplicate `operationId`s, invalid server/external-doc
/// URLs, or empty required fields we don't otherwise patch (e.g. an empty
/// response `description`).
///
/// Deliberately lenient about *unused* components (schemas, parameters,
/// responses, etc., all covered by `IGNORE_UNUSED`) and undeclared tags
/// (`IgnoreMissingTags`): neither affects fuzzing and real-world specs
/// commonly have both, so flagging them would just be noise. External
/// `$ref`s are similarly ignored (`IgnoreExternalReferences`) since we don't
/// fetch them here. This is purely informational -- validation findings
/// never fail the load.
fn warn_about_roas_validation_issues<T: roas::validation::Validate>(spec: &T, filename: &Path) {
    use roas::validation::{IGNORE_UNUSED, Options};

    let options = IGNORE_UNUSED | Options::IgnoreExternalReferences | Options::IgnoreMissingTags;
    if let Err(err) = spec.validate(options, None) {
        warn_with_bullets(
            &format!(
                "OpenAPI spec at {} has {} semantic validation issue(s):",
                filename.to_string_lossy(),
                err.errors.len()
            ),
            &err.errors,
        );
    }
}

/// Parses `contents` as generic JSON and re-serializes it. Object keys that
/// occur more than once within the same object are merged, keeping only the
/// last occurrence, in line with the behaviour of most lenient JSON parsers
/// (and the JSON specification's recommendation). Returns `None` if `contents`
/// isn't valid generic JSON (e.g. because it is YAML, or is empty).
///
/// This is only used as a last-resort retry (see `openapi_from_file`), after
/// all other strategies -- including `roas` on the untouched file -- have
/// already failed, so we don't bother checking whether deduplication actually
/// changed anything before retrying.
fn dedupe_json_object_keys(contents: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(contents).ok()?;
    serde_json::to_string(&value).ok()
}

/// Returns a human-readable, document-order list of the locations (as
/// slash-separated paths from the document root) of object keys that occur
/// more than once within the same JSON object in `contents`. Returns an empty
/// `Vec` if `contents` isn't valid generic JSON, or has no duplicate keys.
///
/// This exists purely to produce an informative warning message when
/// `dedupe_json_object_keys` turns out to have been necessary; the standard
/// `serde_json::Value` deserialization used there silently keeps only the
/// last occurrence of a duplicate key and has no way to report that this
/// happened, so we do a separate, dedicated pass with a custom `Visitor` that
/// tracks the path as it walks the document and records duplicates as they
/// are found.
fn find_duplicate_json_keys(contents: &str) -> Vec<String> {
    let path = RefCell::new(Vec::<String>::new());
    let duplicates = RefCell::new(Vec::<String>::new());
    let mut de = serde_json::Deserializer::from_str(contents);
    let _ = DuplicateKeyFinder {
        path: &path,
        duplicates: &duplicates,
    }
    .deserialize(&mut de);
    duplicates.into_inner()
}

/// `serde` visitor/seed used by `find_duplicate_json_keys` to walk a JSON
/// document, tracking the current path and recording every object key that
/// is encountered more than once within the same object.
struct DuplicateKeyFinder<'a> {
    path: &'a RefCell<Vec<String>>,
    duplicates: &'a RefCell<Vec<String>>,
}

impl<'a> DuplicateKeyFinder<'a> {
    fn child(&self) -> Self {
        DuplicateKeyFinder {
            path: self.path,
            duplicates: self.duplicates,
        }
    }
}

impl<'de, 'a> DeserializeSeed<'de> for DuplicateKeyFinder<'a> {
    type Value = ();

    fn deserialize<D>(self, deserializer: D) -> std::result::Result<Self::Value, D::Error>
    where
        D: serde::de::Deserializer<'de>,
    {
        deserializer.deserialize_any(self)
    }
}

impl<'de, 'a> Visitor<'de> for DuplicateKeyFinder<'a> {
    type Value = ();

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "any valid JSON value")
    }

    fn visit_map<M>(self, mut map: M) -> std::result::Result<Self::Value, M::Error>
    where
        M: MapAccess<'de>,
    {
        let mut seen = HashSet::new();
        while let Some(key) = map.next_key::<String>()? {
            if !seen.insert(key.clone()) {
                let mut full_path = self.path.borrow().clone();
                full_path.push(key.clone());
                self.duplicates.borrow_mut().push(full_path.join("/"));
            }
            self.path.borrow_mut().push(key);
            map.next_value_seed(self.child())?;
            self.path.borrow_mut().pop();
        }
        Ok(())
    }

    fn visit_seq<S>(self, mut seq: S) -> std::result::Result<Self::Value, S::Error>
    where
        S: SeqAccess<'de>,
    {
        let mut index = 0usize;
        loop {
            self.path.borrow_mut().push(format!("[{index}]"));
            let visited = seq.next_element_seed(self.child())?;
            self.path.borrow_mut().pop();
            match visited {
                Some(()) => index += 1,
                None => break,
            }
        }
        Ok(())
    }

    fn visit_bool<E>(self, _v: bool) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
    fn visit_i64<E>(self, _v: i64) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
    fn visit_u64<E>(self, _v: u64) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
    fn visit_f64<E>(self, _v: f64) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
    fn visit_str<E>(self, _v: &str) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
    fn visit_string<E>(self, _v: String) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
    fn visit_unit<E>(self) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
    fn visit_none<E>(self) -> std::result::Result<Self::Value, E> {
        Ok(())
    }
}

/// Generically rewrites Swagger 2.0 constructs that aren't recognized by our
/// parsing crates, wherever they occur anywhere in the document, and returns
/// the re-serialized document together with a human-readable description of
/// each fix, if anything was changed (or `None` if the document couldn't be
/// parsed generically, or nothing needed patching):
///
/// - A schema's non-standard `type: file` (valid only on Swagger 2.0 `body`/
///   `formData` parameters, to indicate a file upload) is rewritten to the
///   OpenAPI 3.0-style equivalent, `{type: string, format: binary}`.
/// - An integer schema's `format`, if it is anything other than the two
///   standard values `int32`/`int64` (e.g. `uint32`, `int8`, as seen in the
///   wild), is dropped, and likewise a number schema's `format` other than
///   `float`/`double`. `format` is purely descriptive/advisory for fuzzing
///   purposes, so losing it is harmless, whereas keeping it causes some
///   parsers (which model `format` as a closed enum for Swagger 2.0) to
///   reject the whole document.
/// - The siblings of a `$ref` other than `summary`/`description` (e.g.
///   `x-ms-client-flatten`, `readOnly`) are dropped. They are ignored in
///   Swagger 2.0 and OpenAPI 3.0 anyway, but `roas` rejects them.
/// - A response without (or with an empty) `description` gets a placeholder.
///   `roas`'s v2 -> v3.0 upgrade panics on it.
fn sanitize_legacy_schema_quirks(contents: &str) -> Option<(String, Vec<String>)> {
    let mut doc = serde_yaml::from_str::<serde_yaml::Value>(contents).ok()?;
    let mut path = Vec::new();
    let mut fixes = Vec::new();
    fix_legacy_schema_quirks(&mut doc, &mut path, &mut fixes);
    if fixes.is_empty() {
        return None;
    }
    let sanitized = serde_yaml::to_string(&doc).ok()?;
    Some((sanitized, fixes))
}

/// Recursively walks `value`, applying the schema fixes described on
/// `sanitize_legacy_schema_quirks`, tracking the current path in `path` and
/// appending a human-readable description of each fix (including its path)
/// to `fixes`.
fn fix_legacy_schema_quirks(
    value: &mut serde_yaml::Value,
    path: &mut Vec<String>,
    fixes: &mut Vec<String>,
) {
    if let serde_yaml::Value::Mapping(map) = value {
        let type_key = serde_yaml::Value::String("type".to_string());
        let format_key = serde_yaml::Value::String("format".to_string());
        let location = || {
            if path.is_empty() {
                "(document root)".to_string()
            } else {
                path.join("/")
            }
        };

        // Siblings of a `$ref` are ignored in v2/v3.0, and roas rejects them. A path
        // item may legitimately combine `$ref` with operations.
        let ref_key = serde_yaml::Value::String("$ref".to_string());
        let is_path_item = path.len() == 2 && path[0] == "paths";
        if map.get(&ref_key).is_some_and(serde_yaml::Value::is_string)
            && map.len() > 1
            && !is_path_item
        {
            let before = map.len();
            map.retain(|k, _| matches!(k.as_str(), Some("$ref" | "summary" | "description")));
            if map.len() < before {
                fixes.push(format!("{}: dropped the siblings of a `$ref`", location()));
            }
        }

        // roas' v2 -> v3.0 upgrade panics on a response without (or with an empty)
        // `description`. Only an operation's responses, and the reusable ones at the
        // root, hold responses; a schema property may also be called `responses`.
        let holds_responses = match path.as_slice() {
            [] => true,
            [first, _, _] => first == "paths",
            _ => false,
        };
        if holds_responses
            && let Some(serde_yaml::Value::Mapping(responses)) = map.get_mut("responses")
        {
            for (code, response) in responses.iter_mut() {
                if let serde_yaml::Value::Mapping(response) = response
                    && !response.contains_key("$ref")
                    && response
                        .get("description")
                        .and_then(serde_yaml::Value::as_str)
                        .is_none_or(str::is_empty)
                {
                    response.insert("description".into(), "No description.".into());
                    fixes.push(format!(
                        "{}/responses/{}: filled in a missing response `description`",
                        location(),
                        code.as_str()
                            .map(str::to_string)
                            .unwrap_or_else(|| format!("{code:?}"))
                    ));
                }
            }
        }

        match map.get(&type_key).cloned() {
            Some(serde_yaml::Value::String(t)) if t == "file" => {
                map.insert(type_key, serde_yaml::Value::String("string".to_string()));
                map.insert(format_key, serde_yaml::Value::String("binary".to_string()));
                fixes.push(format!(
                    "{}: rewrote non-standard `type: file` to `{{type: string, format: binary}}`",
                    location()
                ));
            }
            Some(serde_yaml::Value::String(t)) if t == "integer" || t == "number" => {
                let standard: &[&str] = if t == "integer" {
                    &["int32", "int64"]
                } else {
                    &["float", "double"]
                };
                if let Some(serde_yaml::Value::String(f)) = map.get(&format_key).cloned()
                    && !standard.contains(&f.as_str())
                {
                    map.remove(&format_key);
                    fixes.push(format!(
                        "{}: dropped non-standard {t} `format: {f}`",
                        location()
                    ));
                }
            }
            _ => {}
        }

        for (k, v) in map.iter_mut() {
            path.push(
                k.as_str()
                    .map(str::to_string)
                    .unwrap_or_else(|| format!("{k:?}")),
            );
            fix_legacy_schema_quirks(v, path, fixes);
            path.pop();
        }
    } else if let serde_yaml::Value::Sequence(seq) = value {
        for (i, v) in seq.iter_mut().enumerate() {
            path.push(format!("[{i}]"));
            fix_legacy_schema_quirks(v, path, fixes);
            path.pop();
        }
    }
}

/// Loads the OpenAPI specification from the given path
pub fn get_api_spec(path: &Path) -> Result<Box<Spec>, anyhow::Error> {
    openapi_from_file(path)
        .map(Box::new)
        .with_context(|| format!("Error parsing OpenAPI-file at {}", path.to_string_lossy()))
}

#[cfg(test)]
mod tests {
    use std::io::Write;

    use tempfile::NamedTempFile;

    use super::*;

    /// Helper: write `contents` to a temp file and load it via `openapi_from_file`.
    fn load_spec_from_str(contents: &str) -> Spec {
        let mut file = NamedTempFile::new().unwrap();
        file.write_all(contents.as_bytes()).unwrap();
        openapi_from_file(file.path()).expect("Failed to load spec")
    }

    fn schema_object(schema: &oas3::spec::Schema) -> &oas3::spec::ObjectSchema {
        match schema {
            oas3::spec::Schema::Boolean(_) => panic!("Expected object schema, got boolean schema"),
            oas3::spec::Schema::Object(schema_ref) => match schema_ref.as_ref() {
                oas3::spec::ObjectOrReference::Object(schema) => schema,
                oas3::spec::ObjectOrReference::Ref { .. } => {
                    panic!("Expected concrete schema, got $ref")
                }
            },
        }
    }

    /// Helper: given a loaded Spec, find the schema for a given component name.
    fn get_component_schema<'a>(spec: &'a Spec, name: &str) -> &'a oas3::spec::ObjectSchema {
        let components = spec.components.as_ref().expect("spec has no components");
        schema_object(components.schemas.get(name).expect("schema not found"))
    }

    /// Regression test for specs with a completely empty `info: {}` object
    /// (e.g. bibliothek.json from the WebFuzzing/Dataset benchmark), which
    /// would otherwise fail to parse with "missing field `title`"/"missing
    /// field `version`" under every parsing strategy.
    #[test]
    fn empty_info_object_gets_placeholder_title_and_version() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.1",
                "info": {},
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, DEFAULT_INFO_TITLE);
        assert_eq!(spec.info.version, DEFAULT_INFO_VERSION);
    }

    /// Regression test for specs missing the `info` key entirely (e.g.
    /// blogapi.json-style documents).
    #[test]
    fn missing_info_key_gets_placeholder_title_and_version() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, DEFAULT_INFO_TITLE);
        assert_eq!(spec.info.version, DEFAULT_INFO_VERSION);
    }

    /// A spec with only `title` missing should keep the existing `version`;
    /// only the missing field gets a placeholder.
    #[test]
    fn only_missing_field_is_patched() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "info": { "version": "4.2.0" },
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, DEFAULT_INFO_TITLE);
        assert_eq!(spec.info.version, "4.2.0");
    }

    /// A fully valid spec must be loaded completely unaffected: no placeholder
    /// substitution should occur when `info.title`/`info.version` are present.
    #[test]
    fn well_formed_info_is_left_untouched() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "info": { "title": "My API", "version": "1.2.3" },
                "paths": {}
            }"#,
        );
        assert_eq!(spec.info.title, "My API");
        assert_eq!(spec.info.version, "1.2.3");
    }

    /// Verifies that schema-level `example` (singular, v3.0 keyword) is preserved
    /// across all schema types when loaded via the oas3 path (v3.0 YAML).
    /// The oas3 library stores v3.0's singular `example` in the deprecated `example` field,
    /// not in the v3.1 `examples` Vec.
    #[test]
    fn upgrade_preserves_schema_examples_all_types() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths: {}
components:
  schemas:
    Greeting:
      type: string
      example: "Hello, world!"
    Age:
      type: integer
      example: 42
    Tags:
      type: array
      items:
        type: string
      example: ["alpha", "beta"]
    User:
      type: object
      properties:
        name:
          type: string
          example: "nested@example.com"
        age:
          type: integer
      example:
        name: Alice
        age: 30
"#;
        let spec = load_spec_from_str(spec_yaml);

        // oas3 stores v3.0's singular `example` in the `example` field (deprecated but functional)
        let greeting = get_component_schema(&spec, "Greeting");
        assert_eq!(
            greeting.example,
            Some(serde_json::json!("Hello, world!")),
            "String example lost. example: {:?}",
            greeting.example
        );

        let age = get_component_schema(&spec, "Age");
        assert_eq!(
            age.example,
            Some(serde_json::json!(42)),
            "Integer example lost. example: {:?}",
            age.example
        );

        let tags = get_component_schema(&spec, "Tags");
        assert_eq!(
            tags.example,
            Some(serde_json::json!(["alpha", "beta"])),
            "Array example lost. example: {:?}",
            tags.example
        );

        let user = get_component_schema(&spec, "User");
        assert_eq!(
            user.example,
            Some(serde_json::json!({"name": "Alice", "age": 30})),
            "Object example lost. example: {:?}",
            user.example
        );

        // Nested property example
        let name_schema = schema_object(user.properties.get("name").unwrap());
        assert_eq!(
            name_schema.example,
            Some(serde_json::json!("nested@example.com")),
            "Nested property example lost. example: {:?}",
            name_schema.example
        );
    }

    /// Verifies that MediaType-level examples (on request bodies) are preserved.
    #[test]
    fn upgrade_preserves_media_type_example() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths:
  /items:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example:
              name: "TestItem"
      responses:
        '200':
          description: OK
"#;
        let spec = load_spec_from_str(spec_yaml);
        let operation = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/items")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        let request_body = operation
            .request_body
            .as_ref()
            .unwrap()
            .resolve(&spec)
            .expect("could not resolve request body");
        let media_type = request_body
            .content
            .get("application/json")
            .expect("missing application/json content");
        match &media_type.examples {
            Some(oas3::spec::MediaTypeExamples::Example { example }) => {
                assert_eq!(*example, serde_json::json!({"name": "TestItem"}));
            }
            other => panic!("Expected MediaTypeExamples::Example, got {:?}", other),
        }
    }

    /// Verifies that a v3.1 spec with `examples` (plural, array form) is loaded correctly.
    #[test]
    fn v31_spec_preserves_schema_examples() {
        let spec_yaml = r#"
openapi: "3.1.0"
info:
  title: Test
  version: "1.0"
paths: {}
components:
  schemas:
    Color:
      type: string
      examples:
        - "red"
        - "green"
        - "blue"
"#;
        let spec = load_spec_from_str(spec_yaml);
        let schema = get_component_schema(&spec, "Color");
        assert!(schema.examples.contains(&serde_json::json!("red")));
        assert!(schema.examples.contains(&serde_json::json!("blue")));
    }

    /// Verifies that OpenAPI v3.2 specs (which `oas3`/`openapiv3-extended` don't know
    /// about, since both predate the v3.2 release) are still loaded successfully, via
    /// the `roas` fallback cascade's v3.2 parsing strategy. (OAS 3.2 is a backwards-
    /// compatible extension of 3.1, so this particular minimal spec would also happen
    /// to parse correctly via the v3.1 strategy; the dedicated v3.2 strategy exists so
    /// that genuinely v3.2-only constructs, e.g. the new OAuth2 device-authorization
    /// flow or the `$self` keyword, aren't misparsed or silently dropped by an older,
    /// unaware model.)
    #[test]
    fn v32_spec_is_parsed_via_roas() {
        let spec_yaml = r#"
openapi: "3.2.0"
info:
  title: Test
  version: "1.0"
paths: {}
components:
  schemas:
    Color:
      type: string
      examples:
        - "red"
        - "green"
"#;
        let spec = load_spec_from_str(spec_yaml);
        let schema = get_component_schema(&spec, "Color");
        assert!(schema.examples.contains(&serde_json::json!("red")));
    }

    /// Verifies that `example` on composition schemas (allOf/oneOf/anyOf) is preserved
    /// when going through the openapiv3 upgrade path (Swagger 2.0 forces this path).
    #[test]
    fn upgrade_preserves_example_on_composition_schemas() {
        let spec_json = r#"{
  "swagger": "2.0",
  "info": { "title": "Test", "version": "1.0" },
  "host": "localhost",
  "basePath": "/",
  "paths": {},
  "definitions": {
    "Pet": {
      "allOf": [
        { "type": "object", "properties": { "name": { "type": "string" } } },
        { "type": "object", "properties": { "age": { "type": "integer" } } }
      ],
      "example": { "name": "Fido", "age": 5 }
    },
    "Shape": {
      "oneOf": [
        { "type": "object", "properties": { "radius": { "type": "number" } } },
        { "type": "object", "properties": { "width": { "type": "number" } } }
      ],
      "example": { "radius": 1.4 }
    },
    "Flexible": {
      "anyOf": [
        { "type": "string" },
        { "type": "integer" }
      ],
      "example": "hello"
    }
  }
}"#;
        let spec = load_spec_from_str(spec_json);

        let pet = get_component_schema(&spec, "Pet");
        assert!(
            pet.examples
                .contains(&serde_json::json!({"name": "Fido", "age": 5})),
            "allOf example lost. examples: {:?}",
            pet.examples
        );

        let shape = get_component_schema(&spec, "Shape");
        assert!(
            shape.examples.contains(&serde_json::json!({"radius": 1.4})),
            "oneOf example lost. examples: {:?}",
            shape.examples
        );

        let flexible = get_component_schema(&spec, "Flexible");
        assert!(
            flexible.examples.contains(&serde_json::json!("hello")),
            "anyOf example lost. examples: {:?}",
            flexible.examples
        );
    }

    /// Verifies that parameter-level `example` and parameter schema `example`
    /// are both preserved (v3.0, oas3 path).
    #[test]
    fn upgrade_preserves_parameter_examples() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths:
  /users/{userId}:
    get:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            example: 123
          example: 456
      responses:
        '200':
          description: OK
"#;
        let spec = load_spec_from_str(spec_yaml);
        let operation = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/users/{userId}")
            .unwrap()
            .get
            .as_ref()
            .unwrap();
        let param = operation
            .parameters
            .iter()
            .filter_map(|p| p.resolve(&spec).ok())
            .find(|p| p.name == "userId")
            .expect("userId parameter missing");

        // Parameter-level example (on the Parameter object itself)
        assert_eq!(
            param.example,
            Some(serde_json::json!(456)),
            "Parameter-level example lost"
        );

        // Schema-level example (nested inside the parameter's schema)
        // oas3 stores v3.0's singular `example` in the deprecated `example` field
        let schema = match &param.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on parameter"),
        };
        assert_eq!(
            schema.example,
            Some(serde_json::json!(123)),
            "Parameter schema example lost. example: {:?}",
            schema.example
        );
    }

    /// Verifies that schema examples survive the openapiv3 upgrade path with
    /// deeply nested properties (Swagger 2.0 forces this path).
    #[test]
    fn upgrade_from_swagger2_preserves_schema_examples() {
        let spec_json = r#"{
  "swagger": "2.0",
  "info": { "title": "Test", "version": "1.0" },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/search": {
      "post": {
        "parameters": [{
          "name": "body",
          "in": "body",
          "schema": {
            "type": "object",
            "properties": {
              "query": { "type": "string", "example": "search term" },
              "options": {
                "type": "object",
                "properties": {
                  "limit": { "type": "integer", "example": 50 }
                },
                "example": { "limit": 50 }
              }
            },
            "example": { "query": "test", "options": { "limit": 25 } }
          }
        }],
        "responses": { "200": { "description": "OK" } }
      }
    }
  },
  "definitions": {
    "Status": { "type": "string", "example": "active" }
  }
}"#;
        let spec = load_spec_from_str(spec_json);

        // Component schema example
        let status = get_component_schema(&spec, "Status");
        assert!(
            status.examples.contains(&serde_json::json!("active")),
            "Component schema example lost. examples: {:?}",
            status.examples
        );

        // Body schema (top-level) - The v2 upgrade wraps body params in an object,
        // so the actual schema is nested as a property named "body".
        let operation = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/search")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        let body = operation
            .request_body
            .as_ref()
            .unwrap()
            .resolve(&spec)
            .expect("could not resolve body");
        let wrapper_schema = match &body.content.iter().next().unwrap().1.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on request body"),
        };
        let body_schema = schema_object(wrapper_schema.properties.get("body").unwrap());
        assert!(
            body_schema
                .examples
                .contains(&serde_json::json!({"query": "test", "options": {"limit": 25}})),
            "Body schema example lost. examples: {:?}",
            body_schema.examples
        );

        // Nested property example
        let query_prop = schema_object(body_schema.properties.get("query").unwrap());
        assert!(
            query_prop
                .examples
                .contains(&serde_json::json!("search term")),
            "Nested property example lost. examples: {:?}",
            query_prop.examples
        );

        // Deeply nested property example (options.limit)
        let options_prop = schema_object(body_schema.properties.get("options").unwrap());
        let limit_prop = schema_object(options_prop.properties.get("limit").unwrap());
        assert!(
            limit_prop.examples.contains(&serde_json::json!(50)),
            "Deeply nested example lost. examples: {:?}",
            limit_prop.examples
        );
    }

    /// Compares loading a v3.0 spec via the oas3 path (direct) vs the openapiv3 path
    /// (upgrade). Both paths should produce the same schema data. If they diverge,
    /// it indicates one path is losing data that the other preserves.
    #[test]
    fn v30_oas3_vs_openapiv3_paths_produce_same_schema_data() {
        let spec_yaml = r#"
openapi: "3.0.3"
info:
  title: Test
  version: "1.0"
paths:
  /items/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 7
          example: 42
      responses:
        '200':
          description: OK
components:
  schemas:
    Item:
      type: object
      title: "An Item"
      description: "Represents an item in the store"
      default: { "name": "unnamed", "price": 0 }
      example: { "name": "Widget", "price": 9.99 }
      properties:
        name:
          type: string
          title: "Item name"
          example: "Gadget"
        price:
          type: number
          example: 4.99
    Status:
      type: string
      example: "active"
      default: "pending"
"#;
        // Path 1: oas3 directly (what openapi_from_file does for v3.0)
        let spec_via_oas3: Spec = oas3::from_yaml(spec_yaml)
            .expect("oas3 should parse v3.0")
            .into();

        // Path 2: openapiv3 parse + upgrade (what would happen if oas3 rejected it)
        let spec_via_openapiv3: Spec = serde_yaml::from_str::<VersionedOpenAPI>(spec_yaml)
            .expect("openapiv3 should parse v3.0")
            .upgrade()
            .into();

        // Compare component schemas
        let oas3_components = spec_via_oas3.components.as_ref().unwrap();
        let openapiv3_components = spec_via_openapiv3.components.as_ref().unwrap();

        for schema_name in ["Item", "Status"] {
            let oas3_schema = schema_object(oas3_components.schemas.get(schema_name).unwrap());
            let openapiv3_schema =
                schema_object(openapiv3_components.schemas.get(schema_name).unwrap());

            // oas3 path stores v3.0's singular `example` in deprecated `example` field,
            // openapiv3 conversion stores it in the v3.1 `examples` Vec.
            // Verify both paths preserve the example data (just in different fields).
            let oas3_example = oas3_schema.example.clone();
            let openapiv3_examples = &openapiv3_schema.examples;
            if let Some(ex) = &oas3_example {
                assert!(
                    openapiv3_examples.contains(ex),
                    "Schema '{schema_name}': oas3 has example={:?} but openapiv3 examples={:?}",
                    oas3_example,
                    openapiv3_examples
                );
            }
            assert_eq!(
                oas3_schema.title, openapiv3_schema.title,
                "Schema '{schema_name}' title differs between paths"
            );
            assert_eq!(
                oas3_schema.description, openapiv3_schema.description,
                "Schema '{schema_name}' description differs between paths"
            );
            assert_eq!(
                oas3_schema.default, openapiv3_schema.default,
                "Schema '{schema_name}' default differs between paths"
            );
        }

        // Compare nested property schemas
        let oas3_item = schema_object(oas3_components.schemas.get("Item").unwrap());
        let openapiv3_item = schema_object(openapiv3_components.schemas.get("Item").unwrap());
        for prop_name in ["name", "price"] {
            let oas3_prop = schema_object(oas3_item.properties.get(prop_name).unwrap());
            let openapiv3_prop = schema_object(openapiv3_item.properties.get(prop_name).unwrap());
            let oas3_example = oas3_prop.example.clone();
            let openapiv3_examples = &openapiv3_prop.examples;
            if let Some(ex) = &oas3_example {
                assert!(
                    openapiv3_examples.contains(ex),
                    "Property '{prop_name}': oas3 has example={:?} but openapiv3 examples={:?}",
                    oas3_example,
                    openapiv3_examples
                );
            }
            assert_eq!(
                oas3_prop.title, openapiv3_prop.title,
                "Property '{prop_name}' title differs between paths"
            );
        }

        // Compare parameter data
        let oas3_param = spec_via_oas3
            .paths
            .as_ref()
            .into_iter()
            .flat_map(|map| map.get("/items/{id}"))
            .flat_map(|path_item| path_item.get.as_ref())
            .flat_map(|op| op.parameters.iter())
            .filter_map(|p| p.resolve(&spec_via_oas3).ok())
            .find(|p| p.name == "id")
            .unwrap();
        let openapiv3_param = spec_via_openapiv3
            .paths
            .as_ref()
            .into_iter()
            .flat_map(|map| map.get("/items/{id}"))
            .flat_map(|path_item| path_item.get.as_ref())
            .flat_map(|op| op.parameters.iter())
            .filter_map(|p| p.resolve(&spec_via_openapiv3).ok())
            .find(|p| p.name == "id")
            .unwrap();

        assert_eq!(
            oas3_param.example, openapiv3_param.example,
            "Parameter 'id' example differs.\n  oas3: {:?}\n  openapiv3: {:?}",
            oas3_param.example, openapiv3_param.example
        );
        let oas3_param_schema = match &oas3_param.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on id param in oas3 path"),
        };
        let openapiv3_param_schema = match &openapiv3_param.schema {
            Some(s) => schema_object(s),
            None => panic!("Expected concrete schema on id param in openapiv3 path"),
        };
        let oas3_param_example = oas3_param_schema.example.clone();
        let openapiv3_param_examples = &openapiv3_param_schema.examples;
        if let Some(ex) = &oas3_param_example {
            assert!(
                openapiv3_param_examples.contains(ex),
                "Parameter schema: oas3 has example={:?} but openapiv3 examples={:?}",
                oas3_param_example,
                openapiv3_param_examples
            );
        }
    }

    /// Regression test for Swagger 2.0 specs using `in: formData` parameters
    /// (e.g. languagetool.json from the WebFuzzing/Dataset benchmark), which
    /// neither `oas3` nor `openapiv3`'s v2 support can deserialize (`formData`
    /// isn't a valid v2 parameter location in those crates' models), but
    /// `roas`'s v2 model handles natively.
    #[test]
    fn swagger2_form_data_parameter_is_parsed_via_roas() {
        let spec = load_spec_from_str(
            r#"{
                "swagger": "2.0",
                "info": { "title": "Form data API", "version": "1.0" },
                "paths": {
                    "/check": {
                        "post": {
                            "operationId": "check",
                            "parameters": [
                                {
                                    "name": "text",
                                    "in": "formData",
                                    "type": "string",
                                    "required": false
                                }
                            ],
                            "responses": { "200": { "description": "OK" } }
                        }
                    }
                }
            }"#,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/check")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("check"));
    }

    /// Regression test for specs with a literal duplicate object key within
    /// the same path item (e.g. two `"get"` entries under `/api/albums` in
    /// blogapi.json from the WebFuzzing/Dataset benchmark). `serde_yaml`'s
    /// generic `Value` (used by our own pre-processing) and `roas`'s strict
    /// deserializer both reject such documents outright, so we retry through
    /// a generic `serde_json::Value` round-trip first, which keeps only the
    /// last occurrence of a duplicate key, matching how most lenient JSON
    /// parsers behave.
    ///
    /// This test also uses a boolean `exclusiveMinimum` (valid OpenAPI 3.0 /
    /// JSON Schema draft-4 syntax, as opposed to v3.1's numeric form), to
    /// verify that `roas`'s v3.0 -> v3.1 upgrade correctly translates it.
    #[test]
    fn duplicate_path_item_key_is_resolved_via_last_value() {
        let spec = load_spec_from_str(
            r#"{
                "openapi": "3.0.0",
                "info": { "title": "Duplicate key API", "version": "1.0" },
                "paths": {
                    "/api/albums": {
                        "get": {
                            "operationId": "broken_stub",
                            "responses": { "200": { "description": "stub, should be discarded" } }
                        },
                        "get": {
                            "operationId": "real_operation",
                            "parameters": [
                                {
                                    "name": "page",
                                    "in": "query",
                                    "required": false,
                                    "schema": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "exclusiveMinimum": false
                                    }
                                }
                            ],
                            "responses": { "200": { "description": "OK" } }
                        }
                    }
                }
            }"#,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/api/albums")
            .unwrap()
            .get
            .as_ref()
            .unwrap();
        // The last of the two duplicate `get` keys should win.
        assert_eq!(op.operation_id.as_deref(), Some("real_operation"));
    }

    #[test]
    fn dedupe_json_object_keys_keeps_last_occurrence() {
        let deduped = dedupe_json_object_keys(
            r#"{"a": 1, "nested": {"x": "stub"}, "nested": {"x": "real"}}"#,
        )
        .expect("should be valid JSON");
        let value: serde_json::Value = serde_json::from_str(&deduped).unwrap();
        assert_eq!(value["nested"]["x"], "real");
    }

    #[test]
    fn dedupe_json_object_keys_returns_none_for_yaml() {
        // Plain YAML (not valid as generic JSON) should be rejected, not panic.
        assert!(dedupe_json_object_keys("openapi: 3.0.0\ninfo:\n  title: x\n").is_none());
    }

    /// Regression test for Swagger 2.0's non-standard `type: file` schema
    /// (valid only on `body`/`formData` parameters, to indicate a file
    /// upload, e.g. in proxyprint.json from the WebFuzzing/Dataset
    /// benchmark), which `roas`'s Swagger 2.0 schema model rejects outright
    /// (it only recognizes `type: object` in that position).
    #[test]
    fn swagger2_file_type_parameter_is_parsed_via_roas() {
        // `type: file` used as a *schema property* type (as opposed to a
        // `formData` parameter's own `type`, which `roas` already supports
        // natively) is a non-standard Swagger 2.0 construct seen in
        // `proxyprint.json` from the WebFuzzing/Dataset benchmark: `roas`'s
        // schema model has no `file` variant, so this only parses after
        // `sanitize_legacy_schema_quirks` rewrites it to the OAS3-equivalent
        // `{type: string, format: binary}`.
        let spec = load_spec_from_str(
            r##"{
                "swagger": "2.0",
                "info": { "title": "File upload API", "version": "1.0" },
                "paths": {
                    "/upload": {
                        "post": {
                            "operationId": "upload",
                            "responses": {
                                "200": {
                                    "description": "OK",
                                    "schema": { "$ref": "#/definitions/FileResource" }
                                }
                            }
                        }
                    }
                },
                "definitions": {
                    "FileResource": {
                        "type": "object",
                        "properties": {
                            "file": { "type": "file" }
                        }
                    }
                }
            }"##,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/upload")
            .unwrap()
            .post
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("upload"));
    }

    /// Regression test for non-standard integer `format`s (e.g. `uint32`, as
    /// seen in youtube-mock.yaml from the WebFuzzing/Dataset benchmark), which
    /// `roas`'s Swagger 2.0 schema model restricts to a closed `int32`/`int64`
    /// enum.
    #[test]
    fn non_standard_integer_format_is_parsed_via_roas() {
        // `externalDocs` as a single object (rather than a list) at the
        // document root is valid Swagger 2.0, but trips up a bug in the
        // `openapiv3-extended` crate's v2 model (it expects a list there),
        // forcing a fall-through to the `roas`-based strategies below --
        // mirroring the real-world `youtube-mock.yaml` spec that surfaced
        // this combination of quirks.
        let spec = load_spec_from_str(
            r#"{
                "swagger": "2.0",
                "info": { "title": "Odd format API", "version": "1.0" },
                "externalDocs": { "url": "https://example.com" },
                "paths": {
                    "/count": {
                        "get": {
                            "operationId": "count",
                            "responses": {
                                "200": {
                                    "description": "OK",
                                    "schema": { "type": "integer", "format": "uint32" }
                                }
                            }
                        }
                    }
                }
            }"#,
        );
        let op = spec
            .paths
            .as_ref()
            .unwrap()
            .get("/count")
            .unwrap()
            .get
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("count"));
    }

    #[test]
    fn sanitize_legacy_schema_quirks_rewrites_file_type() {
        let (sanitized, fixes) =
            sanitize_legacy_schema_quirks(r#"{"type": "file", "description": "upload"}"#)
                .expect("should have changed something");
        let value: serde_yaml::Value = serde_yaml::from_str(&sanitized).unwrap();
        assert_eq!(value["type"], serde_yaml::Value::String("string".into()));
        assert_eq!(value["format"], serde_yaml::Value::String("binary".into()));
        assert_eq!(fixes.len(), 1);
        assert!(fixes[0].contains("type: file"));
    }

    #[test]
    fn sanitize_legacy_schema_quirks_drops_non_standard_integer_format() {
        let (sanitized, fixes) =
            sanitize_legacy_schema_quirks(r#"{"type": "integer", "format": "uint32"}"#)
                .expect("should have changed something");
        let value: serde_yaml::Value = serde_yaml::from_str(&sanitized).unwrap();
        assert!(value.get("format").is_none());
        assert_eq!(fixes.len(), 1);
        assert!(fixes[0].contains("uint32"));
    }

    #[test]
    fn sanitize_legacy_schema_quirks_leaves_standard_schemas_untouched() {
        assert!(
            sanitize_legacy_schema_quirks(r#"{"type": "integer", "format": "int32"}"#).is_none()
        );
        assert!(sanitize_legacy_schema_quirks(r#"{"type": "string"}"#).is_none());
    }

    #[test]
    fn sanitize_legacy_schema_quirks_reports_the_path_of_the_fix() {
        let (_, fixes) = sanitize_legacy_schema_quirks(
            r#"{
                "components": {
                    "schemas": {
                        "FileResource": {
                            "properties": {
                                "file": { "type": "file" }
                            }
                        }
                    }
                }
            }"#,
        )
        .expect("should have changed something");
        assert_eq!(fixes.len(), 1);
        assert!(
            fixes[0].starts_with("components/schemas/FileResource/properties/file:"),
            "unexpected fix path: {}",
            fixes[0]
        );
    }

    /// Swagger 2.0 as served by APIs.guru: `$ref` parameters (which
    /// `openapiv3-extended` cannot read), a `$ref` with siblings, a non-standard
    /// number `format`, and a response without `description` (which made roas
    /// panic).
    #[test]
    fn swagger2_ref_siblings_and_missing_description_are_parsed_via_roas() {
        let spec = load_spec_from_str(
            r##"{
                "swagger": "2.0",
                "info": { "title": "t", "version": "1" },
                "parameters": { "id": { "name": "id", "in": "path", "required": true, "type": "string" } },
                "paths": {
                    "/a/{id}": {
                        "get": {
                            "operationId": "getA",
                            "parameters": [
                                { "$ref": "#/parameters/id", "x-ms-parameter-location": "method" }
                            ],
                            "responses": {
                                "200": { "schema": { "type": "number", "format": "decimal" } }
                            }
                        }
                    }
                }
            }"##,
        );
        let op = spec.paths.as_ref().unwrap()["/a/{id}"]
            .get
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("getA"));
    }

    /// roas reads this as Swagger 2.0 without complaint, but its v2 -> v3.0
    /// upgrade panics on the empty response `description` (seen in Azure specs).
    /// The panic must fall through to the sanitized retry, not crash the process.
    #[test]
    fn roas_upgrade_panic_falls_back_to_sanitized_retry() {
        let spec = load_spec_from_str(
            r##"{
                "swagger": "2.0",
                "info": { "title": "t", "version": "1" },
                "parameters": { "id": { "name": "id", "in": "path", "required": true, "type": "string" } },
                "paths": {
                    "/a/{id}": {
                        "get": {
                            "operationId": "getA",
                            "parameters": [{ "$ref": "#/parameters/id" }],
                            "responses": { "200": { "description": "" } }
                        }
                    }
                }
            }"##,
        );
        let op = spec.paths.as_ref().unwrap()["/a/{id}"]
            .get
            .as_ref()
            .unwrap();
        assert_eq!(op.operation_id.as_deref(), Some("getA"));
    }

    #[test]
    fn find_duplicate_json_keys_reports_path_of_duplicates() {
        let duplicates = find_duplicate_json_keys(
            r#"{
                "paths": {
                    "/pets": {
                        "get": { "operationId": "a" },
                        "get": { "operationId": "b" }
                    }
                }
            }"#,
        );
        assert_eq!(duplicates, vec!["paths//pets/get".to_string()]);
    }

    #[test]
    fn find_duplicate_json_keys_returns_empty_for_well_formed_json() {
        assert!(find_duplicate_json_keys(r#"{"a": {"b": 1}}"#).is_empty());
    }
}
