name: Sigrid pull request feedback
on: [pull_request]

jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mark as safe
        run: /usr/bin/git config --global --add safe.directory /github/workspace
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@main
        with:
          customer: TNO
          system: WuppieFuzz
          subsystem: WuppieFuzz
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
      - name: "Sigrid pull request feedback"
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message-id: sigrid
          message-path: sigrid-ci-output/feedback.md
